mc_event:
    resource: "@MCEventBundle/Resources/config/routing.yml"
    prefix:   /mycampus

sino_training:
    resource: "@sinoTrainingBundle/Resources/config/routing.yml"
    prefix:   /training

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /mycampus

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /mycampus/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /mycampus/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /mycampus/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /mycampus/profile